spring.application.name=backend
server.port=8080

spring.config.import=file:C:/Users/Dell/Downloads/FrietSync/backend/.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.cors.allowed-origins=http://localhost:5173,https://friet-sync.vercel.app,https://frietsync.me
app.auth.refresh-cookie.secure=${REFRESH_COOKIE_SECURE}
app.auth.refresh-cookie.same-site=${REFRESH_COOKIE_SAME_SITE}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${REDIS_SSL}  

server.address=127.0.0.1